
            extrn   clearBuffer
            extrn   fillBuffer
            extrn   drawPixel
            extrn   clearPixel
            extrn   drawLine
            extrn   clearLine
            extrn   drawRect
            extrn   clearRect
            extrn   drawBlock
            extrn   clearBlock
            extrn   drawBitmap
            extrn   clearBitmap


;---- debug routines
            extrn gfx_print_buffer
            extrn gfx_print_hex 
