#define     GFX_BG_TRANSPARENT     0
#define     GFX_BG_OPAQUE          1

            extrn   clear_buffer
            extrn   fill_buffer
            extrn   draw_pixel
            extrn   clear_pixel
            extrn   draw_line
            extrn   clear_line
            extrn   draw_rect
            extrn   clear_rect
            extrn   draw_block
            extrn   clear_block
            extrn   draw_bitmap
            extrn   clear_bitmap
            extrn   draw_char
            extrn   draw_string
